package builder

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
)

// EvasionConfig holds evasion-related options for shellcode generation.
type EvasionConfig struct {
	XORKey       bool // 是否添加 XOR 随机密钥加密
	XORKeyLength int  // XOR 密钥长度 (default: 16)
	EncodeHex    bool // 是否 hex 编码输出
	AESWrap      bool // 是否 AES 包裹 (暂不实现，保留选项)
}

// xorEncrypt performs cyclic XOR encryption on data using the provided key.
func xorEncrypt(data []byte, key []byte) []byte {
	result := make([]byte, len(data))
	for i := range data {
		result[i] = data[i] ^ key[i%len(key)]
	}
	return result
}

// xorDecrypt is an alias for xorEncrypt (XOR is symmetric).
func xorDecrypt(data []byte, key []byte) []byte {
	return xorEncrypt(data, key)
}

// generateRandomKey creates a cryptographically random key of the given length.
func generateRandomKey(length int) ([]byte, error) {
	if length <= 0 {
		return nil, fmt.Errorf("key length must be positive, got %d", length)
	}
	key := make([]byte, length)
	if _, err := rand.Read(key); err != nil {
		return nil, fmt.Errorf("failed to generate random key: %w", err)
	}
	return key, nil
}

// wrapWithXORLoader encrypts shellcode with a random XOR key and returns
// (encryptedShellcode, xorKey, error).
func wrapWithXORLoader(shellcode []byte, keyLength int) ([]byte, []byte, error) {
	xorKey, err := generateRandomKey(keyLength)
	if err != nil {
		return nil, nil, err
	}
	encrypted := xorEncrypt(shellcode, xorKey)
	return encrypted, xorKey, nil
}

// generateXORDecoderGoSource generates a Go source code snippet that serves as
// a standalone XOR decoder. The caller can embed this in the implant or compile
// it separately.
//
// The generated code expects:
//   - The encrypted payload to be prepended with the XOR key
//     (format: [keyLen:4 bytes][xorKey][encryptedPayload])
func generateXORDecoderGoSource() string {
	return `// XOR Decoder - Auto-generated by toshell builder
// This file decodes XOR-encrypted shellcode at runtime.
// Format: [keyLen:4 bytes big-endian][xorKey][encryptedPayload]

package main

import (
	"encoding/binary"
	"fmt"
	"os"
)

func xorDecode(data []byte, key []byte) []byte {
	result := make([]byte, len(data))
	for i := range data {
		result[i] = data[i] ^ key[i%%len(key)]
	}
	return result
}

func main() {
	// In a real implant, this would be embedded as a byte slice.
	// This standalone decoder reads from a file for testing purposes.
	if len(os.Args) < 3 {
		fmt.Fprintf(os.Stderr, "Usage: xor_decoder <encrypted_file> <output_file>\n")
		os.Exit(1)
	}

	data, err := os.ReadFile(os.Args[1])
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to read input: %%v\n", err)
		os.Exit(1)
	}

	if len(data) < 4 {
		fmt.Fprintf(os.Stderr, "Input too short\n")
		os.Exit(1)
	}

	keyLen := int(binary.BigEndian.Uint32(data[:4]))
	if keyLen <= 0 || keyLen > 256 {
		fmt.Fprintf(os.Stderr, "Invalid key length: %%d\n", keyLen)
		os.Exit(1)
	}

	if len(data) < 4+keyLen {
		fmt.Fprintf(os.Stderr, "Input too short for key+payload\n")
		os.Exit(1)
	}

	xorKey := data[4 : 4+keyLen]
	payload := data[4+keyLen:]
	decoded := xorDecode(payload, xorKey)

	if err := os.WriteFile(os.Args[2], decoded, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write output: %%v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Decoded %%d bytes successfully.\n", len(decoded))
}
`
}

// PrependXORKey prepends the XOR key with its length to the encrypted payload.
// Format: [keyLen:4 bytes big-endian][xorKey][encryptedPayload]
func PrependXORKey(encryptedPayload []byte, xorKey []byte) []byte {
	keyLen := len(xorKey)
	// 4 bytes for key length (big-endian) + key + encrypted payload
	result := make([]byte, 4+keyLen+len(encryptedPayload))

	// Write key length as big-endian uint32
	result[0] = byte(keyLen >> 24)
	result[1] = byte(keyLen >> 16)
	result[2] = byte(keyLen >> 8)
	result[3] = byte(keyLen)

	copy(result[4:], xorKey)
	copy(result[4+keyLen:], encryptedPayload)

	return result
}

// XORDecodeShellcode decodes shellcode that was encrypted and prepended with the key.
// Input format: [keyLen:4 bytes big-endian][xorKey][encryptedPayload]
func XORDecodeShellcode(encoded []byte) ([]byte, error) {
	if len(encoded) < 4 {
		return nil, fmt.Errorf("encoded data too short (len=%d)", len(encoded))
	}

	keyLen := int(uint32(encoded[0])<<24 | uint32(encoded[1])<<16 | uint32(encoded[2])<<8 | uint32(encoded[3]))
	if keyLen <= 0 || keyLen > 256 {
		return nil, fmt.Errorf("invalid key length: %d", keyLen)
	}

	if len(encoded) < 4+keyLen {
		return nil, fmt.Errorf("encoded data too short for key+payload (need %d, got %d)", 4+keyLen, len(encoded))
	}

	xorKey := encoded[4 : 4+keyLen]
	payload := encoded[4+keyLen:]

	return xorDecrypt(payload, xorKey), nil
}

// ConvertShellcodeToHex converts raw shellcode bytes to hex string format.
func ConvertShellcodeToHex(shellcode []byte) string {
	return hex.EncodeToString(shellcode)
}
